import { Router, type IRouter } from "express";
import healthRouter from "./health";
import publicConfigRouter from "./public-config";
import clientsRouter from "./clients";
import projectsRouter from "./projects";
import tasksRouter from "./tasks";
import teamRouter from "./team";
import messagesRouter from "./messages";
import filesRouter from "./files";
import quotesRouter from "./quotes";
import contractsRouter from "./contracts";
import contractDocumentsRouter from "./contract-documents";
import clientContractsRouter from "./client-contracts";
import dashboardRouter from "./dashboard";
import metaRouter from "./meta";
import reportsRouter from "./reports";
import aiChatRouter from "./ai-chat";
import aiRouter from "./ai";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import rolesRouter from "./roles";
import emailNotificationsRouter from "./email-notifications";
import googleAdsRouter from "./google-ads";
import teamClientAccessRouter from "./team-client-access";
import searchRouter from "./search";
import deadlinesRouter from "./deadlines";
import activityLogRouter from "./activity-log";
import clientBriefsRouter from "./client-briefs";
import editorialPlansRouter from "./editorial-plans";
import dailyFocusRouter from "./daily-focus";
import timeTrackerRouter from "./time-tracker";
import trashRouter from "./trash";

const router: IRouter = Router();

router.use(healthRouter);
router.use(publicConfigRouter);
router.use(clientsRouter);
router.use(projectsRouter);
router.use(tasksRouter);
router.use(teamRouter);
router.use(messagesRouter);
router.use(filesRouter);
router.use(quotesRouter);
router.use(contractsRouter);
router.use(contractDocumentsRouter);
router.use(clientContractsRouter);
router.use(dashboardRouter);
router.use(metaRouter);
router.use(reportsRouter);
router.use(aiChatRouter);
router.use(aiRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(rolesRouter);
router.use(emailNotificationsRouter);
router.use(googleAdsRouter);
router.use(teamClientAccessRouter);
router.use(searchRouter);
router.use(deadlinesRouter);
router.use(activityLogRouter);
router.use(clientBriefsRouter);
router.use(editorialPlansRouter);
router.use(dailyFocusRouter);
router.use(timeTrackerRouter);
router.use(trashRouter);

export default router;
